// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: building.proto

#include "building.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Building::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        street_{nullptr},
        number_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Building::Building(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BuildingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildingDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildingDefaultTypeInternal() {}
  union {
    Building _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildingDefaultTypeInternal _Building_default_instance_;
static ::_pb::Metadata file_level_metadata_building_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_building_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_building_2eproto = nullptr;
const ::uint32_t TableStruct_building_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::Building, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::Building, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Building, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::Building, _impl_.number_),
    PROTOBUF_FIELD_OFFSET(::Building, _impl_.street_),
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::Building)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_Building_default_instance_._instance,
};
const char descriptor_table_protodef_building_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016building.proto\032\014street.proto\"A\n\010Buildi"
    "ng\022\014\n\004name\030\001 \001(\t\022\016\n\006number\030\002 \001(\r\022\027\n\006stre"
    "et\030\003 \001(\0132\007.Streetb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_building_2eproto_deps[1] =
    {
        &::descriptor_table_street_2eproto,
};
static ::absl::once_flag descriptor_table_building_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_building_2eproto = {
    false,
    false,
    105,
    descriptor_table_protodef_building_2eproto,
    "building.proto",
    &descriptor_table_building_2eproto_once,
    descriptor_table_building_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_building_2eproto::offsets,
    file_level_metadata_building_2eproto,
    file_level_enum_descriptors_building_2eproto,
    file_level_service_descriptors_building_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_building_2eproto_getter() {
  return &descriptor_table_building_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_building_2eproto(&descriptor_table_building_2eproto);
// ===================================================================

class Building::_Internal {
 public:
  using HasBits = decltype(std::declval<Building>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Building, _impl_._has_bits_);
  static const ::Street& street(const Building* msg);
  static void set_has_street(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::Street& Building::_Internal::street(const Building* msg) {
  return *msg->_impl_.street_;
}
void Building::clear_street() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.street_ != nullptr) _impl_.street_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Building::Building(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Building)
}
inline PROTOBUF_NDEBUG_INLINE Building::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

Building::Building(
    ::google::protobuf::Arena* arena,
    const Building& from)
    : ::google::protobuf::Message(arena) {
  Building* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.street_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::Street>(arena, *from._impl_.street_)
                : nullptr;
  _impl_.number_ = from._impl_.number_;

  // @@protoc_insertion_point(copy_constructor:Building)
}
inline PROTOBUF_NDEBUG_INLINE Building::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void Building::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, street_),
           0,
           offsetof(Impl_, number_) -
               offsetof(Impl_, street_) +
               sizeof(Impl_::number_));
}
Building::~Building() {
  // @@protoc_insertion_point(destructor:Building)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Building::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.street_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Building::Clear() {
// @@protoc_insertion_point(message_clear_start:Building)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.street_ != nullptr);
    _impl_.street_->Clear();
  }
  _impl_.number_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Building::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 21, 2> Building::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Building, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Building_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Building, _impl_.name_)}},
    // uint32 number = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Building, _impl_.number_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Building, _impl_.number_)}},
    // .Street street = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(Building, _impl_.street_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Building, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 number = 2;
    {PROTOBUF_FIELD_OFFSET(Building, _impl_.number_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .Street street = 3;
    {PROTOBUF_FIELD_OFFSET(Building, _impl_.street_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Street>()},
  }}, {{
    "\10\4\0\0\0\0\0\0"
    "Building"
    "name"
  }},
};

::uint8_t* Building::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Building)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Building.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // uint32 number = 2;
  if (this->_internal_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_number(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .Street street = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, _Internal::street(this),
        _Internal::street(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Building)
  return target;
}

::size_t Building::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Building)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // .Street street = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.street_);
  }

  // uint32 number = 2;
  if (this->_internal_number() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Building::_class_data_ = {
    Building::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Building::GetClassData() const {
  return &_class_data_;
}

void Building::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Building*>(&to_msg);
  auto& from = static_cast<const Building&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Building)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_street()->::Street::MergeFrom(
        from._internal_street());
  }
  if (from._internal_number() != 0) {
    _this->_internal_set_number(from._internal_number());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Building::CopyFrom(const Building& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Building)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Building::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Building::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Building::InternalSwap(Building* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Building, _impl_.number_)
      + sizeof(Building::_impl_.number_)
      - PROTOBUF_FIELD_OFFSET(Building, _impl_.street_)>(
          reinterpret_cast<char*>(&_impl_.street_),
          reinterpret_cast<char*>(&other->_impl_.street_));
}

::google::protobuf::Metadata Building::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_building_2eproto_getter, &descriptor_table_building_2eproto_once,
      file_level_metadata_building_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
