// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: address.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Address {

  /// <summary>Holder for reflection information generated from address.proto</summary>
  public static partial class AddressReflection {

    #region Descriptor
    /// <summary>File descriptor for address.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AddressReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1hZGRyZXNzLnByb3RvEgdhZGRyZXNzGgpjaXR5LnByb3RvGgxzdHJlZXQu",
            "cHJvdG8aDmJ1aWxkaW5nLnByb3RvImkKB0FkZHJlc3MSGAoEY2l0eRgBIAEo",
            "CzIKLmNpdHkuQ2l0eRIeCgZzdHJlZXQYAiABKAsyDi5zdHJlZXQuU3RyZWV0",
            "EiQKCGJ1aWxkaW5nGAMgASgLMhIuYnVpbGRpbmcuQnVpbGRpbmdiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::City.CityReflection.Descriptor, global::Street.StreetReflection.Descriptor, global::Building.BuildingReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Address.Address), global::Address.Address.Parser, new[]{ "City", "Street", "Building" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Address : pb::IMessage<Address>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Address> _parser = new pb::MessageParser<Address>(() => new Address());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Address> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Address.AddressReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address(Address other) : this() {
      city_ = other.city_ != null ? other.city_.Clone() : null;
      street_ = other.street_ != null ? other.street_.Clone() : null;
      building_ = other.building_ != null ? other.building_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Address Clone() {
      return new Address(this);
    }

    /// <summary>Field number for the "city" field.</summary>
    public const int CityFieldNumber = 1;
    private global::City.City city_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::City.City City {
      get { return city_; }
      set {
        city_ = value;
      }
    }

    /// <summary>Field number for the "street" field.</summary>
    public const int StreetFieldNumber = 2;
    private global::Street.Street street_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Street.Street Street {
      get { return street_; }
      set {
        street_ = value;
      }
    }

    /// <summary>Field number for the "building" field.</summary>
    public const int BuildingFieldNumber = 3;
    private global::Building.Building building_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Building.Building Building {
      get { return building_; }
      set {
        building_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Address);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Address other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(City, other.City)) return false;
      if (!object.Equals(Street, other.Street)) return false;
      if (!object.Equals(Building, other.Building)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (city_ != null) hash ^= City.GetHashCode();
      if (street_ != null) hash ^= Street.GetHashCode();
      if (building_ != null) hash ^= Building.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (city_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(City);
      }
      if (street_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Street);
      }
      if (building_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Building);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (city_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(City);
      }
      if (street_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Street);
      }
      if (building_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Building);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (city_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(City);
      }
      if (street_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Street);
      }
      if (building_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Building);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Address other) {
      if (other == null) {
        return;
      }
      if (other.city_ != null) {
        if (city_ == null) {
          City = new global::City.City();
        }
        City.MergeFrom(other.City);
      }
      if (other.street_ != null) {
        if (street_ == null) {
          Street = new global::Street.Street();
        }
        Street.MergeFrom(other.Street);
      }
      if (other.building_ != null) {
        if (building_ == null) {
          Building = new global::Building.Building();
        }
        Building.MergeFrom(other.Building);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (city_ == null) {
              City = new global::City.City();
            }
            input.ReadMessage(City);
            break;
          }
          case 18: {
            if (street_ == null) {
              Street = new global::Street.Street();
            }
            input.ReadMessage(Street);
            break;
          }
          case 26: {
            if (building_ == null) {
              Building = new global::Building.Building();
            }
            input.ReadMessage(Building);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (city_ == null) {
              City = new global::City.City();
            }
            input.ReadMessage(City);
            break;
          }
          case 18: {
            if (street_ == null) {
              Street = new global::Street.Street();
            }
            input.ReadMessage(Street);
            break;
          }
          case 26: {
            if (building_ == null) {
              Building = new global::Building.Building();
            }
            input.ReadMessage(Building);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
