// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: street.proto

#include "street.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace street {

inline constexpr Street::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        city_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Street::Street(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StreetDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreetDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreetDefaultTypeInternal() {}
  union {
    Street _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreetDefaultTypeInternal _Street_default_instance_;
}  // namespace street
static ::_pb::Metadata file_level_metadata_street_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_street_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_street_2eproto = nullptr;
const ::uint32_t TableStruct_street_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::street::Street, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::street::Street, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::street::Street, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::street::Street, _impl_.city_),
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::street::Street)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::street::_Street_default_instance_._instance,
};
const char descriptor_table_protodef_street_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014street.proto\022\006street\032\ncity.proto\"0\n\006St"
    "reet\022\014\n\004name\030\001 \001(\t\022\030\n\004city\030\002 \001(\0132\n.city."
    "Cityb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_street_2eproto_deps[1] =
    {
        &::descriptor_table_city_2eproto,
};
static ::absl::once_flag descriptor_table_street_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_street_2eproto = {
    false,
    false,
    92,
    descriptor_table_protodef_street_2eproto,
    "street.proto",
    &descriptor_table_street_2eproto_once,
    descriptor_table_street_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_street_2eproto::offsets,
    file_level_metadata_street_2eproto,
    file_level_enum_descriptors_street_2eproto,
    file_level_service_descriptors_street_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_street_2eproto_getter() {
  return &descriptor_table_street_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_street_2eproto(&descriptor_table_street_2eproto);
namespace street {
// ===================================================================

class Street::_Internal {
 public:
  using HasBits = decltype(std::declval<Street>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Street, _impl_._has_bits_);
  static const ::city::City& city(const Street* msg);
  static void set_has_city(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::city::City& Street::_Internal::city(const Street* msg) {
  return *msg->_impl_.city_;
}
void Street::clear_city() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.city_ != nullptr) _impl_.city_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Street::Street(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:street.Street)
}
inline PROTOBUF_NDEBUG_INLINE Street::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

Street::Street(
    ::google::protobuf::Arena* arena,
    const Street& from)
    : ::google::protobuf::Message(arena) {
  Street* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.city_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::city::City>(arena, *from._impl_.city_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:street.Street)
}
inline PROTOBUF_NDEBUG_INLINE Street::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void Street::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.city_ = {};
}
Street::~Street() {
  // @@protoc_insertion_point(destructor:street.Street)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Street::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  delete _impl_.city_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Street::Clear() {
// @@protoc_insertion_point(message_clear_start:street.Street)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.city_ != nullptr);
    _impl_.city_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Street::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 26, 2> Street::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Street, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Street_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .city.City city = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Street, _impl_.city_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Street, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(Street, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .city.City city = 2;
    {PROTOBUF_FIELD_OFFSET(Street, _impl_.city_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::city::City>()},
  }}, {{
    "\15\4\0\0\0\0\0\0"
    "street.Street"
    "name"
  }},
};

::uint8_t* Street::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:street.Street)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "street.Street.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .city.City city = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, _Internal::city(this),
        _Internal::city(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:street.Street)
  return target;
}

::size_t Street::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:street.Street)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // .city.City city = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.city_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Street::_class_data_ = {
    Street::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Street::GetClassData() const {
  return &_class_data_;
}

void Street::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Street*>(&to_msg);
  auto& from = static_cast<const Street&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:street.Street)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_city()->::city::City::MergeFrom(
        from._internal_city());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Street::CopyFrom(const Street& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:street.Street)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Street::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Street::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Street::InternalSwap(Street* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  swap(_impl_.city_, other->_impl_.city_);
}

::google::protobuf::Metadata Street::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_street_2eproto_getter, &descriptor_table_street_2eproto_once,
      file_level_metadata_street_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace street
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
